import { Barlow_Condensed, Inter_Tight } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["900"],
  variable: "--font-barlow-condensed",
});

export const metadata = {
  title: "Telzen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${barlowCondensed.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
